/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tenniscourtapp;

import javax.swing.JPanel;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.URL;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author winnann20
 */
public class MapView extends javax.swing.JPanel {

    /**
     * Creates new form MapView
     */
    public MapView() {
        initComponents();
    }
    void createMapView(JFrame parent) {
//AIzaSyDUV-xhoNdbssAdwyVDBsyC71JjXQQ-Mew
        try {
            String imageUrl = "https://maps.googleapis.com/maps/api/staticmap?center=47.6052007,-122.093358&zoom=11&size=612x612&scale=2&maptype=roadmap&key=AIzaSyDUV-xhoNdbssAdwyVDBsyC71JjXQQ-Mew";            
            String destinationFile = "image.jpg";
            String str = destinationFile;
            URL url = new URL(imageUrl);
            InputStream is = url.openStream();
            OutputStream os = new FileOutputStream(destinationFile);

            byte[] b = new byte[2048];
            int length;

            while ((length = is.read(b)) != -1) {
                os.write(b, 0, length);
            }

            is.close();
            os.close();
        } catch (IOException e) {
            e.printStackTrace();
            System.exit(1);
        }

        parent.add(new JLabel(new ImageIcon((new ImageIcon("image.jpg")).getImage().getScaledInstance(750,700,
                java.awt.Image.SCALE_SMOOTH))));

        parent.setVisible(true);
        parent.pack();

//        MapView view = new MapView();
//        parent.add(view);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
